### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by philrz** [brimdata/zui#2838]
Repro is with Zui commit 2e952f9.

Steps shown in the attached video:

1. Import the [prs.json test data](https://github.com/brimdata/zed/blob/main/docs/tutorials/prs.json) from the Zed repo.
2. Enter Zed query `over this | typeof(this)`

The error `TypeError: Cannot read properties of null (reading 'length')` appears along with a stack trace.

https://github.com/brimdata/zui/assets/5934157/81c0bf0d-41db-4eaa-bd6b-7f4d75b4e1c8

The full stack trace:

```
TypeError: Cannot read properties of null (reading 'length')
    at TypeRecordView.iterate (webpack-internal:///./src/app/features/inspector/views/type-record-view.ts:24:47)
    at iterate.next (<anonymous>)
    at TypeRecordView.renderLine (webpack-internal:///./src/app/features/inspector/views/container-view.ts:63:18)
    at TypeRecordView.render (webpack-internal:///./src/app/features/inspector/views/container-view.ts:98:29)
    at TypeRecordView.inspect (webpack-internal:///./src/app/features/inspector/views/container-view.ts:36:18)
    at Cell.inspect (webpack-internal:///./src/components/zed-table/cell.ts:56:19)
    at eval (webpack-internal:///./src/components/zed-table/cell-component.tsx:51:18)
    at startTransition (webpack-internal:///../../node_modules/react/cjs/react.development.js:2429:5)
    at eval (webpack-internal:///./src/components/zed-table/cell-component.tsx:50:63)
    at commitHookEffectListMount (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22964:26)
    at commitPassiveMountOnFiber (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24697:13)
    at commitPassiveMountEffects_complete (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24661:9)
    at commitPassiveMountEffects_begin (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24648:7)
    at commitPassiveMountEffects (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24636:3)
    at flushPassiveEffectsImpl (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26843:3)
    at flushPassiveEffects (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26796:14)
    at commitRootImpl (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26747:5)
    at commitRoot (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26512:5)
    at performSyncWorkOnRoot (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:25951:3)
    at flushSyncCallbacks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11982:22)
    at eval (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:25485:13)
```

**Comment by philrz** [comment]
I've confirmed via binary search that this was fixed as of commit 67797fd, which is associated with the changes in #2996. As shown in the attached video, repeating the original repro steps no longer triggers the error and stack trace. Indeed, I can now see that this issue reads as a duplicate of #2997.

https://github.com/brimdata/zui/assets/5934157/8c7bd2b5-ef2e-458b-833b-35fbc2c38819

Thanks @jameskerr!
