### ISSUE TITLE
Crash when editing "month" portion of time range pin

### ISSUE THREAD

**Issue by philrz** [brimdata/zui#2853]
This issue was reported in a [community Slack thread](https://brimdata.slack.com/archives/C010DR0HHMF/p1696443245779609). Repro is with Zui commit 52f115e.

In the attached video, data is imported and a time range pin is created by dragging a portion of the stacked bar chart. I then click to view/edit the time range pin, then click in the "month" portion of a time range endpoint. Once I hit backspace with intent to change it, a stack dump appears.

https://github.com/brimdata/zui/assets/5934157/6bc22f5f-f772-409d-a4a3-36035266df80

```
TypeError: Cannot read properties of undefined (reading 'text')
    at date.parseInZone (webpack-internal:///./src/js/lib/date.ts:60:23)
    at getTimeString (webpack-internal:///./src/app/query-home/search-area/pins/time-range-pin/get-time-string.ts:10:76)
    at Form (webpack-internal:///./src/app/query-home/search-area/pins/time-range-pin/form.tsx:140:98)
    at renderWithHooks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:16141:18)
    at updateFunctionComponent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:20308:20)
    at beginWork (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22351:16)
    at beginWork$1 (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:27214:14)
    at performUnitOfWork (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26387:12)
    at workLoopSync (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26298:5)
    at renderRootSync (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26266:7)
    at recoverFromConcurrentError (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:25684:20)
    at performSyncWorkOnRoot (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:25930:20)
    at flushSyncCallbacks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11982:22)
    at flushSync (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26035:7)
    at finishEventHandler (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3969:5)
    at batchedUpdates (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3987:5)
    at dispatchEventForPluginEventSystem (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:9257:3)
    at dispatchEvent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:6435:5)
    at dispatchDiscreteEvent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:6410:5)
```

**Comment by philrz** [comment]
Verified in Zui commit 9c77e24.

As shown in the attached video, now the "month" portion of the date range endpoint can be successfully edited without crashing.

https://github.com/brimdata/zui/assets/5934157/f38c1d49-e88d-4300-a8db-1285a8e2c05b
