### ISSUE TITLE
Attempt to output null record type causes "TypeError: Cannot read properties of null (reading 'length')"

### ISSUE THREAD

**Issue by philrz** [brimdata/zui#2997]
Repro is with Zui commit 205c88c. @mccanne found this issue while shaping some GitHub data for a presentatoin.

As shown in the attached video, attempting a `yield typeof({})` produces a stack trace.

https://github.com/brimdata/zui/assets/5934157/69f20a62-c8af-4448-9490-62b77f949954

The full stack trace:

```
TypeError: Cannot read properties of null (reading 'length')
    at TypeRecordView.iterate (webpack-internal:///./src/app/features/inspector/views/type-record-view.ts:24:47)
    at iterate.next (<anonymous>)
    at TypeRecordView.renderLine (webpack-internal:///./src/app/features/inspector/views/container-view.ts:63:18)
    at TypeRecordView.render (webpack-internal:///./src/app/features/inspector/views/container-view.ts:98:29)
    at TypeRecordView.inspect (webpack-internal:///./src/app/features/inspector/views/container-view.ts:36:18)
    at Cell.inspect (webpack-internal:///./src/components/zed-table/cell.ts:56:19)
    at eval (webpack-internal:///./src/components/zed-table/cell-component.tsx:51:18)
    at startTransition (webpack-internal:///../../node_modules/react/cjs/react.development.js:2429:5)
    at eval (webpack-internal:///./src/components/zed-table/cell-component.tsx:50:63)
    at commitHookEffectListMount (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:22964:26)
    at commitPassiveMountOnFiber (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24697:13)
    at commitPassiveMountEffects_complete (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24661:9)
    at commitPassiveMountEffects_begin (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24648:7)
    at commitPassiveMountEffects (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:24636:3)
    at flushPassiveEffectsImpl (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26843:3)
    at flushPassiveEffects (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26796:14)
    at performSyncWorkOnRoot (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:25910:3)
    at flushSyncCallbacks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:11982:22)
    at commitRootImpl (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26771:3)
    at commitRoot (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:26512:5)
    at finishConcurrentRender (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:25815:9)
    at performConcurrentWorkOnRoot (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:25643:7)
    at workLoop (webpack-internal:///../../node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (webpack-internal:///../../node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///../../node_modules/scheduler/cjs/scheduler.development.js:533:21)
```

**Comment by philrz** [comment]
Verified in Zui commit 8088f5c.

As shown in the attached video, now a `yield typeof({})` produces the expected output without stack trace.

https://github.com/brimdata/zui/assets/5934157/6efb0d47-769e-44f8-a02d-b319e1711bb0

Thanks @jameskerr!
