### ISSUE TITLE
Stack trace: Cannot read properties of null (reading 'queryId')

### ISSUE THREAD

**Issue by philrz** [brimdata/zui#3161]
Repro is with Zui Insiders release [1.18.1-insiders.10](https://github.com/brimdata/zui-insiders/releases/tag/v1.18.1-insiders.10).

Steps as shown in the attached video:

1. Start Zui Insiders fresh with no prior app state
2. Load some data
3. Run a simple query such as `count()`
4. Quit the app
5. Relaunch the app
6. Click to the tab where I previously ran the query.

https://github.com/user-attachments/assets/9ec9d770-69df-4dbc-937f-b851ea7307f5

The stack trace that appears:

```
TypeError: Cannot read properties of null (reading 'queryId')
    at app-asset://zui/_next/static/chunks/857-2e02d01d5db559fa.js:1:48356
    at app-asset://zui/_next/static/chunks/65-6cd3697cf1efaa42.js:35:32035
    at a (app-asset://zui/_next/static/chunks/65-6cd3697cf1efaa42.js:35:30829)
    at app-asset://zui/_next/static/chunks/65-6cd3697cf1efaa42.js:35:32206
    at a (app-asset://zui/_next/static/chunks/65-6cd3697cf1efaa42.js:35:30829)
    at t (app-asset://zui/_next/static/chunks/65-6cd3697cf1efaa42.js:35:409)
    at app-asset://zui/_next/static/chunks/65-6cd3697cf1efaa42.js:35:614
    at Object.useSyncExternalStore (app-asset://zui/_next/static/chunks/framework-d2a24e5002b8cad4.js:9:67443)
    at n.useSyncExternalStore (app-asset://zui/_next/static/chunks/framework-d2a24e5002b8cad4.js:25:6223)
    at e.useSyncExternalStoreWithSelector (app-asset://zui/_next/static/chunks/65-6cd3697cf1efaa42.js:35:683)
```

When it's in this state, it seems like the history associated with the tab that now shows the stack trace is doomed, as once I close it, it's purged from the Sessions list.

I can only seem to repro this with Zui Insiders, though. For instance, if I start the app via `yarn` at commit f265410 (the same commit on which Zui Insiders release [1.18.1-insiders.10](https://github.com/brimdata/zui-insiders/releases/tag/v1.18.1-insiders.10) is based) I don't see the stack trace and when I close such a tab the entry remains in the Sessions list.

**Comment by philrz** [comment]
Verified in Zui Insiders release [1.18.1-insiders.12](https://github.com/brimdata/zui-insiders/releases/tag/v1.18.1-insiders.12).

Repeating the repro steps in the attached video, the stack trace no longer appears after we relaunch the app and click to the browser tab for our previous session.

https://github.com/user-attachments/assets/766aacb8-89a7-4742-b867-6f46d3e36eb4

Thanks @jameskerr!
